import './NgoaiCanhScreen.css'
import { player } from '../../data/character.js'

const areas = [
  {name:'Rừng Rậm Ven Hồ',min:1,max:10,icon:'🌲',terrain:'Rừng hồ',monsters:[['Huyết Lang',5,7],['Linh Hầu',6,8],['Thủy Yêu Tiểu Ngư',8,10]]},
  {name:'Bạch Thủy Động',min:6,max:15,icon:'💧',terrain:'Hang động',monsters:[['Động Quật Xà',8,10],['Bạch Thủy Yêu',10,13],['Thạch Quỷ',12,15]]},
  {name:'Sơn Tặc Trại',min:11,max:20,icon:'⛺',terrain:'Sơn trại',monsters:[['Sơn Tặc',12,15],['Sơn Tặc Đầu Mục',14,18],['Cuồng Đao Khách',17,20]]},
  {name:'Thanh Xà Cốc',min:16,max:25,icon:'🐍',terrain:'Thung lũng',monsters:[['Thanh Xà',17,20],['Thanh Xà Yêu',19,23],['Xà Vương Thủ Vệ',22,25]]},
  {name:'Vũ Lăng Sơn',min:21,max:30,icon:'⛰️',terrain:'Núi rừng',monsters:[['Hắc Hùng',22,25],['Sơn Viên',24,28],['Vũ Lăng Yêu Binh',27,30]]},
  {name:'Thiên Nhẫn Cốc',min:26,max:40,icon:'🦂',terrain:'Cốc địa',monsters:[['Thiên Nhẫn Đệ Tử',28,32],['Hắc Hạt',31,35],['Ma Cốc Sát Thủ',35,40]]},
  {name:'Võ Đang Sơn',min:36,max:50,icon:'☯️',terrain:'Đạo sơn',monsters:[['Võ Đang Kiếm Sĩ',38,41],['Thanh Phong Đạo Nhân',41,46],['Huyền Vũ Thủ Sơn',46,50]]},
  {name:'Đường Môn Cổ Địa',min:46,max:60,icon:'🎯',terrain:'Cổ địa',monsters:[['Đường Môn Đệ Tử',48,52],['Độc Tiễn Thủ',51,56],['Cơ Quan Thú',56,60]]},
  {name:'Dược Vương Cốc',min:56,max:70,icon:'🌿',terrain:'Linh cốc',monsters:[['Dược Cốc Linh Đồng',58,61],['Độc Vật',61,66],['Dược Vương Thủ Hộ',66,70]]},
  {name:'Lão Hổ Động',min:66,max:80,icon:'🐯',terrain:'Sơn động',monsters:[['Lão Hổ',68,72],['Hổ Yêu',71,76],['Hổ Vương',76,80]]},
  {name:'Tần Lăng',min:76,max:90,icon:'🏛️',terrain:'Cổ lăng',monsters:[['Tần Lăng Vệ Binh',78,82],['Lăng Mộ Quỷ',81,86],['Thiên Cổ Thi',86,90]]},
  {name:'Phù Dung Động',min:86,max:105,icon:'🔥',terrain:'Địa huyệt',monsters:[['Phù Dung Yêu',88,92],['Hỏa Linh',92,98],['Phù Dung Ma Tướng',98,105]]},
  {name:'Phong Lăng Độ',min:101,max:120,icon:'⛵',terrain:'Bến nước',monsters:[['Phong Lăng Thủy Tặc',103,108],['Hắc Phong Thủy Quỷ',107,114],['Phong Lăng Đầu Mục',114,120]]},
  {name:'Huyết Sa Mạc',min:116,max:140,icon:'🏜️',terrain:'Sa mạc',monsters:[['Huyết Sa Đạo Tặc',118,123],['Sa Mạc Yêu Binh',122,130],['Huyết Ma Kỵ Sĩ',130,140]]},
  {name:'Thiên Sơn Tuyết Cốc',min:136,max:160,icon:'❄️',terrain:'Tuyết vực',monsters:[['Tuyết Lang',138,143],['Băng Giáp Thú',142,150],['Thiên Sơn Tuyết Yêu',150,160]]},
  {name:'Côn Lôn Sơn',min:156,max:180,icon:'🏔️',terrain:'Côn Lôn',monsters:[['Côn Lôn Kiếm Khách',158,164],['Huyền Băng Yêu',163,172],['Côn Lôn Ma Tướng',172,180]]},
  {name:'Vạn Độc Cốc',min:176,max:200,icon:'☠️',terrain:'Độc cốc',monsters:[['Vạn Độc Đệ Tử',178,183],['Thiên Diện Độc Trùng',182,192],['Vạn Độc Ma Quân',192,200]]},
]

const WORLD_STATE_KEY='game.world.state.v1'
function loadState(){try{return JSON.parse(localStorage.getItem(WORLD_STATE_KEY))||{area:0}}catch{return{area:0}}}
function saveState(state){localStorage.setItem(WORLD_STATE_KEY,JSON.stringify(state))}
function canEnter(area){const level=Number(player.level)||1;return level>=area.min-5&&level<=area.max+5}
function recommended(area){const level=Number(player.level)||1;if(level<area.min-5)return `Cần khoảng Lv.${area.min-5} trở lên`;if(level>area.max+5)return `Khu vực thấp hơn Lv.${level}`;if(level<area.min)return `Hơi cao hơn cấp đề nghị · Lv.${area.min}–${area.max}`;if(level>area.max)return `Hơi thấp hơn cấp đề nghị · Lv.${area.min}–${area.max}`;return `Phù hợp Lv.${level}`}
function mapMarkup(selected){return `<div class="world-map"><div class="world-map-title">BẢN ĐỒ NGOẠI CẢNH</div><div class="world-map-subtitle">Các khu vực luyện công phân bố theo cấp độ nhân vật</div><div class="world-route"></div>${areas.map((area,i)=>{const x=10+(i%5)*20,y=25+Math.floor(i/5)*22,ok=canEnter(area);return `<button class="world-node${i===selected?' active':''}${ok?'':' locked'}" style="left:${x}%;top:${y}%" type="button" data-area="${i}" ${ok?'':'disabled'}><span class="world-node-icon">${area.icon}</span><span class="world-node-name">${area.name}</span><span class="world-node-level">Lv.${area.min}–${area.max}</span></button>`}).join('')}<div class="world-legend">🟢 Có thể vào · 🔒 Chưa đủ cấp · Chênh lệch tối đa ±5 Lv.</div></div>`}
function detailMarkup(area,state){const ok=canEnter(area),index=areas.indexOf(area);return `<aside class="world-detail"><div class="world-detail-head"><div class="world-detail-name">${area.icon} ${area.name}</div><div class="world-detail-level">Cấp khu vực Lv.${area.min}–${area.max} · ${area.terrain}</div></div><div class="world-detail-body"><section class="world-section"><div class="world-section-title">THÔNG TIN KHU VỰC</div><div class="world-current">Cấp nhân vật: <b>Lv.${player.level}</b></div><div class="world-current" style="margin-top:5px">Trạng thái: <b>${recommended(area)}</b></div><div class="world-current" style="margin-top:5px">Khu vực dùng để <b>luyện công</b> và là điểm đến cho các <b>nhiệm vụ</b>.</div></section><section class="world-section"><div class="world-section-title">QUÁI VẬT KHU VỰC</div>${area.monsters.map(m=>`<div class="world-monster"><span class="world-monster-name">${m[0]}</span><span class="world-monster-level">Lv.${m[1]}–${m[2]}</span></div>`).join('')}</section><section class="world-section"><div class="world-section-title">HOẠT ĐỘNG</div><div class="world-current">• Luyện công và săn quái</div><div class="world-current" style="margin-top:5px">• Nhiệm vụ quái vật có thể yêu cầu đến khu vực này</div><div class="world-current" style="margin-top:5px">• Có thể phát sinh mục tiêu truy nã tại khu vực</div></section><div class="world-detail-actions"><button class="world-action" type="button" data-action="enter" ${ok?'':'disabled'}>${state.area===index?'ĐANG Ở ĐÂY':'ĐI TỚI KHU VỰC'}</button><button class="world-action secondary" type="button" data-action="train" ${ok?'':'disabled'}>LUYỆN CÔNG</button></div></div></aside>`}
export function NgoaiCanhScreen(){return `<div class="world-screen"><div class="world-toolbar"><span class="world-toolbar-title">◆ NGOẠI CẢNH</span><span class="world-toolbar-info">Chọn khu vực phù hợp để luyện công, làm nhiệm vụ và săn quái</span></div><div id="world-content" class="world-layout"></div></div>`}
export function mountNgoaiCanhScreen(){const root=document.querySelector('.world-screen');if(!root)return;const content=root.querySelector('#world-content'),state=loadState();let selected=Math.min(Math.max(Number(state.area)||0,0),areas.length-1);function render(){content.innerHTML=mapMarkup(selected)+detailMarkup(areas[selected],state);bind()}function bind(){root.querySelectorAll('.world-node:not(:disabled)').forEach(btn=>btn.addEventListener('click',()=>{selected=Number(btn.dataset.area);render()}));root.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const area=areas[selected];if(!canEnter(area))return;state.area=selected;saveState(state);const action=btn.dataset.action;window.dispatchEvent(new CustomEvent('game:world-changed',{detail:{name:area.name,level:`Lv.${area.min}-${area.max}`}}));window.dispatchEvent(new CustomEvent('game:log',{detail:{message:action==='train'?`Bắt đầu luyện công tại ${area.name}.`:`Đã di chuyển đến ${area.name}.`,type:'item'}}));render()}))}render()}
