import './NhiemVuScreen.css'
import { player } from '../../data/character.js'

// Nhiệm vụ quái vật luôn trỏ tới quái đang tồn tại thật trong đúng map Ngoại cảnh.
export const monsterTemplates = [
  { name:'Săn Huyết Lang', map:'Rừng Rậm Ven Hồ', target:'Huyết Lang', min:1, max:10, baseCount:30 },
  { name:'Quét Bạch Thủy Động', map:'Bạch Thủy Động', target:'Động Quật Xà', min:6, max:15, baseCount:36 },
  { name:'Săn Hắc Hổ', map:'Hắc Hổ Lâm', target:'Hắc Hổ', min:11, max:20, baseCount:40 },
  { name:'Trừ Thanh Xà', map:'Thanh Xà Cốc', target:'Thanh Xà', min:16, max:25, baseCount:45 },
  { name:'Dẹp Hắc Hùng', map:'Vũ Lăng Sơn', target:'Hắc Hùng', min:21, max:30, baseCount:55 },
  { name:'Dẹp Sơn Tặc Đầu Mục', map:'Dược Vương Cốc', target:'Sơn Tặc Đầu Mục', min:61, max:70, baseCount:70 },
  { name:'Thanh Trừ Ác Tặc', map:'Tần Lăng', target:'Huyết Sát Ác Tặc', min:81, max:90, baseCount:80 },
  { name:'Diệt Xích Viêm Ác Tặc', map:'Phù Dung Động', target:'Xích Viêm Ác Tặc', min:91, max:100, baseCount:90 },
  { name:'Quét Thiên Sơn Tuyết Yêu', map:'Thiên Sơn Tuyết Cốc', target:'Thiên Sơn Tuyết Yêu', min:131, max:150, baseCount:200 },
  { name:'Đại Trừ Vạn Độc Ma Tu', map:'Vạn Độc Cốc', target:'Vạn Độc Ma Tu', min:176, max:200, baseCount:240 },
]

export const wanted = [
  {name:'Hắc Phong Đao Khách',level:'Lv.55',map:'Đường Môn Cổ Địa',reward:'2.500 EXP · 3.000 vàng · Đan dược ×2 · Linh dược ×8'},
  {name:'Huyết Ảnh Ma Nhân',level:'Lv.68',map:'Dược Vương Cốc',reward:'3.200 EXP · 4.500 vàng · Đan dược ×2 · Linh dược ×10'},
  {name:'Thiết Diện Quỷ',level:'Lv.78',map:'Lão Hổ Động',reward:'5.000 EXP · 7.000 vàng · Đan dược ×3 · Linh dược ×12'},
  {name:'Bạch Cốt Khách',level:'Lv.96',map:'Phù Dung Động',reward:'7.500 EXP · 10.000 vàng · Đan dược ×3 · Linh dược ×15'},
  {name:'Xích Viêm Cuồng Đồ',level:'Lv.125',map:'Huyết Sa Mạc',reward:'10.000 EXP · 15.000 vàng · Đan dược ×4 · Linh dược ×18'},
]

const QUEST_STATE_KEY='game.quest.state.v1'
function loadState(){try{const state=JSON.parse(localStorage.getItem(QUEST_STATE_KEY))||{};return{monster:Array.isArray(state.monster)?state.monster:[],monsterProgress:state.monsterProgress&&typeof state.monsterProgress==='object'?state.monsterProgress:{},wanted:state.wanted??null,wantedCount:Number(state.wantedCount||0)}}catch{return{monster:[],monsterProgress:{},wanted:null,wantedCount:0}}}
function saveState(state){localStorage.setItem(QUEST_STATE_KEY,JSON.stringify(state))}
function countForLevel(template){const level=Number(player.level)||1;if(level>=90)return Math.max(200,Math.min(300,template.baseCount+Math.floor((level-90)/10)*5));if(level>50)return Math.max(60,Math.min(100,template.baseCount));return Math.max(30,Math.min(60,template.baseCount))}
function levelDistance(template){const level=Number(player.level)||1;return level>=template.min-5&&level<=template.max+5}
function monsterQuests(){return monsterTemplates.map((q,i)=>({...q,count:countForLevel(q),suitable:levelDistance(q),reward:`${(800+i*350).toLocaleString('vi-VN')} vàng · Linh dược ×${Math.max(3,Math.floor((i+3)/2))}`}))}
function monsterView(state){const quests=monsterQuests(),activeIds=new Set(state.monster||[]);return `<div class="quest-summary"><span>⚔ Đang nhận: <b>${activeIds.size}/2</b></span><span>Nhận nhiệm vụ cả ngày · Không giới hạn số lần nhận</span></div><div class="quest-list" role="list">${quests.map((q,i)=>{const active=activeIds.has(i),progress=Math.min(q.count,Number(state.monsterProgress[i]||0)),completed=progress>=q.count,disabled=completed||activeIds.size>=2||!q.suitable;return `<article class="quest-card${!q.suitable?' quest-not-suitable':''}" role="listitem"><div class="quest-avatar">⚔</div><div class="quest-body"><div class="quest-name">${q.name}</div><div class="quest-meta">📍 ${q.map} · Lv.${q.min}–${q.max}<br>🎯 ${q.target} · <b>${q.count} con</b></div><div class="quest-progress">Tiêu diệt: <strong>${progress}/${q.count}</strong></div><div class="quest-reward">🎁 ${q.reward}</div></div><div class="quest-choice">${q.suitable?`<span class="quest-suitable">${completed?'HOÀN THÀNH':'Phù hợp Lv. '+player.level}</span>`:'<span class="quest-unsuitable">Ngoài cấp độ</span>'}<button class="quest-action" type="button" data-type="monster" data-index="${i}" ${disabled?'disabled':''}>${completed?'HOÀN THÀNH':active?'ĐANG NHẬN':activeIds.size>=2&&q.suitable?'ĐÃ ĐỦ 2 NHIỆM VỤ':'NHẬN NHIỆM VỤ'}</button></div></article>`}).join('')}</div>`}
function wantedView(state){const hasWanted=state.wanted!==null&&state.wanted!==undefined;return `<div class="quest-summary"><span>☠ Truy nã hôm nay: <b>${state.wantedCount||0}/10</b></span><span>🔄 Làm mới sau: <b id="wanted-timer">01:00:00</b></span></div><div class="wanted-grid" role="list">${wanted.map((q,i)=>{const selected=hasWanted&&Number(state.wanted)===i;const disabled=!selected&&(hasWanted||(state.wantedCount||0)>=10);return `<article class="wanted-card${selected?' wanted-active':''}" role="listitem"><div class="wanted-head"><div class="quest-avatar">☠</div><div><div class="wanted-name">${q.name}</div><div class="wanted-badge">Boss nhỏ · ${q.level}</div></div></div><div class="wanted-map">📍 ${q.map}<br>🔎 Khả năng gặp: <b>Thấp</b><br>☠ Mục tiêu: <b>${q.name}</b></div><div class="wanted-rewards">🎁 ${q.reward}</div><div class="wanted-status">${selected?`Đang truy nã ${q.name} tại ${q.map}...`:`Mục tiêu ${q.name} chưa được phát hiện...`}</div><button class="quest-action${selected?' quest-cancel':''}" type="button" data-type="wanted" data-index="${i}" ${disabled?'disabled':''}>${selected?'HỦY NHIỆM VỤ':hasWanted?'KHÔNG THỂ NHẬN':'NHẬN TRUY NÃ'}</button></article>`}).join('')}</div>`}
export function NhiemVuScreen(){return `<div class="quest-screen"><div class="quest-tabs"><button class="quest-tab active" data-tab="monster">⚔ NHIỆM VỤ QUÁI VẬT</button><button class="quest-tab" data-tab="wanted">☠ TRUY NÃ</button></div><div id="quest-content"></div></div>`}
export function mountNhiemVuScreen(){const root=document.querySelector('.quest-screen');if(!root)return;const content=root.querySelector('#quest-content'),state=loadState();let seconds=3600,currentTab='monster';function render(){content.innerHTML=currentTab==='wanted'?wantedView(state):monsterView(state);bindActions()}function bindActions(){root.querySelectorAll('.quest-action').forEach(btn=>btn.addEventListener('click',()=>{const type=btn.dataset.type,index=Number(btn.dataset.index);if(type==='monster'){state.monster=Array.isArray(state.monster)?state.monster:[];const progress=Number(state.monsterProgress[index]||0);const quest=monsterQuests()[index];if(progress>=quest.count){return}if(state.monster.length>=2||state.monster.includes(index))return;state.monster.push(index);state.monsterProgress[index]=progress;saveState(state);window.dispatchEvent(new CustomEvent('game:log',{detail:{message:`Đã nhận nhiệm vụ quái vật: ${monsterTemplates[index].name} — ${monsterTemplates[index].target} tại ${monsterTemplates[index].map}.`,type:'item'}}))}else{const hasWanted=state.wanted!==null&&state.wanted!==undefined;if(hasWanted&&Number(state.wanted)===index){state.wanted=null;saveState(state);window.dispatchEvent(new CustomEvent('game:log',{detail:{message:`Đã hủy truy nã: ${wanted[index].name}.`,type:'item'}}))}else{if(hasWanted||(state.wantedCount||0)>=10)return;state.wanted=index;state.wantedCount=(state.wantedCount||0)+1;saveState(state);window.dispatchEvent(new CustomEvent('game:log',{detail:{message:`Đã nhận truy nã: ${wanted[index].name} — tìm tại ${wanted[index].map}.`,type:'item'}}))}}render()}))}root.querySelectorAll('.quest-tab').forEach(tab=>tab.addEventListener('click',()=>{currentTab=tab.dataset.tab;root.querySelectorAll('.quest-tab').forEach(t=>t.classList.toggle('active',t===tab));render()}));const timer=setInterval(()=>{if(!document.body.contains(root)){clearInterval(timer);return}seconds=Math.max(0,seconds-1);const el=root.querySelector('#wanted-timer');if(el){const h=String(Math.floor(seconds/3600)).padStart(2,'0'),m=String(Math.floor(seconds%3600/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');el.textContent=`${h}:${m}:${s}`}if(seconds===0){seconds=3600;state.wanted=null;saveState(state);if(currentTab==='wanted')render()}},1000);window.addEventListener('game:quest-progress-changed',()=>{const fresh=loadState();state.monster=fresh.monster;state.monsterProgress=fresh.monsterProgress;state.wanted=fresh.wanted;state.wantedCount=fresh.wantedCount;if(document.body.contains(root))render()});render()}
